### ISSUE TITLE
[Android] Crash on screen navigation

### ISSUE THREAD

**Issue by Wunsz** [idrisssakhi/blurView#6] opened 2022-06-17 12:51 UTC
The app is crashing without error when navigating to a screen in which blur is rendered immediately using react-navigation.

This is a duplicate from:
[https://github.com/Kureev/react-native-blur/issues/461](https://github.com/Kureev/react-native-blur/issues/461)

My packages versions:

```
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "rn-id-blurview": "^1.1.1",
```

**Comment by idrisssakhi** [comment] 2022-06-19 17:33
The issue is related to calculating screen position whene animation is enabled.
you can listen to transitionEnd event of navigation before rendering the Blur. While rendering, you can render a simple View. i know this is not the best solution. But i will dig into it when i have some free time.
Don’t hesitate to open PR if you have time.

**Comment by idrisssakhi** [comment] 2022-07-05 08:35
@Wunsz this issue is resolved in the new version of react-native-screens 3.14.0. please update your sdk so you can use this library correctly

**Closed as completed by idrisssakhi** 2022-07-05 08:35 UTC
